# Generated by Django 2.2.16 on 2020-12-09 05:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20201209_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion_corta'),
        ),
    ]
